### ISSUE TITLE
Please include LICENSE file in gem

### ISSUE THREAD

**Issue by voxik** [ckruse/CFPropertyList#35]
Although your repository contains LICENSE file, this file is not shipped in gem. Could you please add the file into the gem? Thank you.

**Comment by ckruse** [comment]
Just as a file? in the files array?

**Comment by voxik** [comment]
Yes, that would be exactly it.

**Comment by voxik** [comment]
Thank you

**Comment by ckruse** [comment]
Thank you for the feedback!
