### ISSUE TITLE
Prettify XML option?

### ISSUE THREAD

**Issue by kenn** [ckruse/CFPropertyList#37]
Generated XML has a single line with the plist.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><array><array><string>woman</string><string>female</string></array><array><string>man</string><string>male</string></array></array></plist>
```

Is it possible to have (indented) line feeds?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <array>
    <array>
      <string>woman</string>
      <string>female</string>
    </array>
    <array>
      <string>man</string>
      <string>male</string>
    </array>
  </array>
</plist>
```

Because it's easier to track diff on git, and also easier to browse the content on text editors / github.

**Comment by ckruse** [comment]
Yes you can, there is a `:formatted` option for the `to_str` and `save` methods:

    plist.to_str(CFPropertyList::List::FORMAT_XML, :formatted => true)
    plist.save('test.plist', CFPropertyList::List::FORMAT_XML, :formatted => true)

**Comment by ckruse** [comment]
I guess this solves your issue and thus I close it. Feel free to re-open if problems occur!
