### ISSUE TITLE
Any specific reason to use NOENT?

### ISSUE THREAD

**Issue by shubhampathak** [ckruse/CFPropertyList#55]
@ckruse Hi Christian, found `NOENT` in both `rbLibXMLParser.rb` and `rbNokogiriParser.rb` 
Passing NOENT as parsing option is risky.

Passing `NOENT` (which is used to substitute entities) as parsing options permits processing of entities, including both regular and external. That means `NONET` and `NODTDLOAD` will be of no use if NOENT is there.

Take a look at this:
https://github.com/sparklemotion/nokogiri/issues/1582#issuecomment-562180275

This is why Nokogiri team strictly suggests using default parsing options:
DEFAULT_XML  = RECOVER | NONET

![NOENT](https://user-images.githubusercontent.com/8207/70249380-52a84680-174a-11ea-86d3-957eccda81d4.png)

**Comment by ckruse** [comment]
Hm. I actually don't remember anymore. It is several years ago that I wrote this code. Following the links you posted it seems to make sense to disable it. Do you mind to create a pull request?

**Comment by shubhampathak** [comment]
Hi Christian, thanks for the quick response. Sure! creating a Pull Request.

**Comment by ckruse** [comment]
fixed by #56

**Comment by ckruse** [comment]
I pushed a new version
