### ISSUE TITLE
Missing cfpropertylist.gemspec file 

### ISSUE THREAD

**Issue by bartoszkosiorek-tomtom** [ckruse/CFPropertyList#58]
It will be great to add cfpropertylist.gemspec which will allow to build with other systems (like pkgsrc).

https://rubygems.org/gems/CFPropertyList/versions/2.3.2

**Comment by ckruse** [comment]
Sorry that I took so long to react, I'm overwhelmed with work…

Although the gem specification was available in the `Rakefile` since you are not the first asking for this I moved it to a .gemspec file

Thanks for your contribution!
