### ISSUE TITLE
Add `nkf` to gemspec

### ISSUE THREAD

**Issue by kapitoshka438** [ckruse/CFPropertyList#66]
After upgrading to Ruby 3.3.0 running `bundle install` for a single Gemfile which only contains Fastlane gem shows this warning
```
{PROJECT_ROOT}/vendor/bundle/ruby/3.3.0/gems/CFPropertyList-3.0.6/lib/cfpropertylist/rbCFPropertyList.rb:3: warning: kconv is found in nkf, which will no longer be part of the default gems since Ruby 3.4.0. Add nkf to your Gemfile or gemspec. Also contact author of CFPropertyList-3.0.6 to add nkf into its gemspec.
```

**Comment by ckruse** [comment]
Should be fixed now, at least I no longer can reproduce it on my dev machine. Can you confirm?

**Comment by kapitoshka438** [comment]
After taking a look on your changes I can assume that it will work for Ruby 3.4.0 (which is not released yet) but it won't fix the Ruby 3.3.0 warning. But it's probably fine.

**Comment by ckruse** [comment]
Sorry, I remembered it wrong. You are right, should be specified for 3.3, too.

**Comment by ckruse** [comment]
Ok, I pushed a new version to rubygems. Thank you for your report! :heart:
